### ISSUE TITLE
new backup gem version needs more libraries

### ISSUE THREAD

**Issue by ramonskie** [damm/backup#26]
with the new backup gem (i tried it with the latest 4.1.10)
it needs more libraries for ubuntu 14.04 (did not test others yet)
```
package 'liblzma-dev'
package 'zlib1g-dev'
```

if these packages are not installed nokogiri will fail

**Comment by damm** [comment]
Hi

We can totally add those packages @ramonskie, sounds like nokogiri except the backup gem.  But either way we'll need to have it.

**Comment by ramonskie** [comment]
Should i make a pull request for you?

**Comment by damm** [comment]
If you'd like; or i'll get around to it tomorrow likely.

**Comment by damm** [comment]
@ramonskie i opened a pull request; looks fine in kitchen any reason not to merge it?

**Comment by ramonskie** [comment]
no i don't see any
seems fine to me
