### ISSUE TITLE
Thoughts on other backup cookbook?

### ISSUE THREAD

**Issue by patcon** [damm/backup#28]
Hey! Thanks for this cookbook! I'm just wondering whether the maintainers of the separate cookbooks might be willing to merge efforts under a single banner. Do you think your approaches are reconcilable?

https://github.com/gofullstack/backup-cookbook

cc: @guilhem @smith @damm

**Comment by damm** [comment]
@patcon There's some history here behind these cookbooks.

Pretty much; no I really don't see that happening.  fujin forked my cookbook into heavywater and then uploaded it to http://cookbooks.opscode.com/cookbooks/backup.

... he eventually offered it up to anyone; I asked and was ignored.  

There's more to it than that but it's not worth stating.

Lastly if I could go back; I would have emailed fujin asking him to revert his fork of my cookbook and to tell heavywater to use my version of the cookbook.  If they wanted to improve the cookbook they should send pull requests.

P.S. Yes I use this cookbook daily; it's another reason I would be nervous.  I depend on it; it must work and it must work correctly.

**Comment by patcon** [comment]
Hm. OK, that's fair.

To be honest, there are a hand-full of thing I would hope to submit as PR's, but (correct me if I'm wrong) it sounds like you're looking to be pretty conservative with changes.

But anyhow, for specifics, here was what I'd prefer to add/alter:
- travis test-kitchen test for testing all platforms and use-cases I use
- A less opinionated template with less hardcoded attributes, so that it's more like the other cookbook
- make metadata name align with community name so won't confuse berkshelf
- reset repo so that it's the canonical and not a fork (as github penalizes it in search results and condemns it to never being "official-looking")

Thoughts on this stuff? I was hoping test coverage might make you more amenable to changes, but I'd rather know in advance before putting effort in :)

Thanks for your time @damm

**Comment by patcon** [comment]
Ah, just realized I was mixed up in my tabs, and you already have integration test coverage :)

**Comment by damm** [comment]
@patcon I just don't like lazy / slopy changes.  I have a tendency to rework someones pull request to my liking.

1. I do use test-kitchen; but I don't use travis.ci; I have seen several rather ugly methods of using travis.ci and test-kitchen on digitalocean or rackspace.  I wish it did not have to be so :(
1. Use 'cookbook' to pass your own erb template.
1. I don't care; I wish the Cookbooks site allowed namespaces so I could just have damm/backup.  I once had the backup slot; I don't know because of another user.
1. It was a fork; I forked a really crappy backup cookbook and made it something.  That's on github not me.


As far as your other concerns;

**Comment by patcon** [comment]
Ok, rockin. Looking through, it doesn't seem like your template is actually losing any functionality despite being not quite so free-form. I'll give it a shot.

I'd love to help get travis running with a badge, if you're down for it.

It sounds silly, but the fork thing is pretty important for me, as I want to get my client on the cookbook that I can help make the go-to backup cookbook. I feel like it being a fork is enough to dissuade a good few people from using it, should they stumble across it while exploring options.

Apparently it can be promoted by emailing support:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

Would you be willing to email support, or could I do it on your behalf?

Thanks for humouring me on this..! :)

**Comment by damm** [comment]
make separate issues and I can email github

**Comment by patcon** [comment]
:+1:

**Comment by damm** [comment]
#29 has been handled feel free to create issues/pull requests on anything you think would be helpful.  I'll respond in 24hours typically (or less) to the issue/pull request.

**Comment by patcon** [comment]
Amazing. I'll submit PR's when I started migrating our custom backup scripts

**Comment by damm** [comment]
Refs ramonskie/bamboo#32
