### ISSUE TITLE
Release v0.2.4 (and new release?) to supermarket

### ISSUE THREAD

**Issue by patcon** [damm/backup#31]
Merging #30 first would be awesome if the premise of it works for you. This would allow me to update the community bamboo cookbook to not need special treatment of this cookbook in the chef-repo berksfile :)

**Comment by damm** [comment]
How about 0.2.5? :)

**Comment by damm** [comment]
https://supermarket.chef.io/cookbooks/backup_lwrp

**Comment by patcon** [comment]
Thanks @damm :)

**Comment by ramonskie** [comment]
@damm are you going to keep the backup_lwrp up to date in the supermarket?
and did the chef-support responded already for the takeover for the obsolete backup cookbook in there supermarket?

**Comment by damm** [comment]
@ramonskie yeah it looks like someone else got the backup cookbook as fujin gave it to someone else.

I don't release often enough to not keep it up to date? I know I have been lazy in the past; but it's not much of a chore now.

**Comment by ramonskie** [comment]
and these cookbooks can't be merged or something?
because i think why we didn't used backup_lwrp
because of the naming inside this cookbook but need to test this again

**Comment by damm** [comment]
Right; if we change the name to backup_lwrp the methods become backup_lwrp_install

I actually don't find that appealing; too many _'s :(

**Comment by patcon** [comment]
`kibana_lwrp` cookbook handles it somehow, creating resources like `kibana_web` and `kibana_user`

https://github.com/lusis/chef-kibana/blob/master/metadata.rb

**Comment by damm** [comment]
@patcon that's using `libraries/` that is not a lwrp; it is a hwrp.  (heavy vs light).

**Comment by damm** [comment]
I recently deployed Kibana 4 and I looked over that cookbook and found it too heavy (opinionated) to use; so I ended up making my own cookbook in a few lines.

My preference is cookbooks I can slap a wrapper around that don't expect any node attributes to be set.  I can set attributes in wrappers but cookbooks like Logstash and Graphite tend to make you wince at the attributes.

**Comment by patcon** [comment]
I'm with you on the attr overuse :) I just wanted to learn enough from it to fix the resource naming we didn't like, re: `backup_lwrp_*`

Might it be possible to rename to `backup_lwrp`, and add a tiny HWRP in `libraries/install.rb` that extend's `Resource::BackupInstall < Resource::BackupLwrpInstall` along with their providers? Would that be too much ugly wrangling? I took a stab, but lack the knowledge of chef internal to get it working :/

**Comment by damm** [comment]
I don't like to write HWRP's.  So you'd have to look elsewhere for that.

You take on too much knowledge; and assumptions that can change in the future of Chef versions.  It may not; but that's a horrible spot to be in.

**Comment by ramonskie** [comment]
@damm i think we still need to contact chef about the abandoned cookbook.

because none of the users that are listed don't even have the cookbook in there repository anymore
maby we can ask @guilhem to transfer it to us
