### ISSUE TITLE
Simplify options hash? (ie. escaped quotes)

### ISSUE THREAD

**Issue by patcon** [damm/backup#32]
Hey @damm, would you consider it a step backward if the cookbook made assumptions about how to write the config file based on the type of the value passed here:
https://github.com/damm/backup/blob/master/templates/default/generic_model.conf.erb#L59-L61

I was thinking something like this might allow for cleaner syntax when using the resource:

```erb
  <% if @backup_type == "database" %>
  database <%= @database_type %> do |db|
  <% @options.each_pair do |k,v| %>
    <% if k.is_a?(String) %>
    <%= k %> = "<%= v %>"
    <% else # Fixnum/Array %>
    <%= k %> = <%= v.to_s %>
    <% end %>
  <% end %>
  end
  <% end %>
```

But I'm not as experienced with the backup gem, so perhaps it breaks other option values, so def let me know if it's not possible :)

**Comment by damm** [comment]
I'll get back to you on this; I think a pull request to see this would be good too.

**Comment by patcon** [comment]
:+1: ended up using a custom template for my current work, but I'm sure i'll be back to this later

**Comment by damm** [comment]
I looked over the immense documentation and options and I quickly realized I likely would not make every option easily available; so I had to provide a way for (you) to work around something I had not expected.

**Comment by damm** [comment]
Any update on this? or safe to close?

**Comment by patcon** [comment]
Sure thing. I'm using a custom template, so not working on it myself
