### ISSUE TITLE
Leverage zap cookbook

### ISSUE THREAD

**Issue by patcon** [damm/backup#37]
The zap pattern is used to specifically clear out old [config] files that originate outside the current chef run's resource collection.

To explain, I was intending to include variable information in the backup model's name, so that it was included in the final tar archive filename. (This would allow for simple metadata, e.g. app version, to be available at a glance). But then I realized that it would mean that old model config files and cron definitions (named from the model name) would linger around. The zap resource would make sure that the old model configs and cron definitions would be removed if the current chef run hadn't touched them.

Would this be something you think would be helpful to others if I put together a PR? (It would require a prior PR to the the zap cookbook: https://github.com/nvwls/zap/issues/28)

**Comment by damm** [comment]
You did notice I added `:disable` and `:remove` actions to `backup_generate_model` right?
https://github.com/damm/backup/blob/master/providers/generate_model.rb#L69

That's a hard problem with Chef cookbooks is people like to remove a resource from the cookbook; leaving the file unmanaged on the server.  My attempt was `:disable` and `:remove`

If you have a different use point or want to enhance this so it's better; I'll be glad to help anyway you need it.

**Comment by patcon** [comment]
Yep, I had seen that, but was more suggesting to protect users from silly mistakes :) I hadn't considered having unmanaged config was a practice to design around, but I suppose it would step on those toes, so probably could close this if that's important?

**Comment by damm** [comment]
It's a nice idea; I think Chef should provide a way to manage the unmanaged resources better.  I don't think we need to close this issue unless you want? 

zap is a neat idea; I just think it should be closer to Chef if we want to use it.

**Comment by patcon** [comment]
Good point. Just created an issue in regards to that thought:
https://github.com/chef/chef/issues/3956

**Comment by damm** [comment]
Once that issue is resolved maybe we can revisit this
