### ISSUE TITLE
Allow install of backup gem from forks/PRs via `specific_install`

### ISSUE THREAD

**Issue by patcon** [damm/backup#38]
There's a feature of backup gem in a PR that I'd like to use. Any chance you'd be willing to entertain the idea of using backup gem forks?

https://github.com/backup/backup-features/issues/33
https://github.com/guilhem-cookbooks/gem_specific_install

**Comment by damm** [comment]
@patcon that's why I provided the multiple functions like `backup_install` `generate_config` and `generate_model`.  They are patterns to help you provide a system to backup with; sometimes you step out and you need x.

We could expand the scope of `backup_install` to specify a github repo and branch?

**Comment by patcon** [comment]
> We could expand the scope of backup_install to specify a github repo and branch?

If you'd be alright with that, I'm happy to submit a PR. Just wanted to make sure you didn't think it'd be overloading the cookbook :)

**Comment by damm** [comment]
I do think it is close to overloading the cookbook; if your in a private organization you might have a different way to install it.  What if your organization generated an omnibus package? 

My experience on the diamond cookbook is sometimes people like to install forks and you eventually want support on going back to mainline (once whatever you forked for is fixed).

So on this thought train.

```ruby
backup_install node.name do
  action :git
  uri "git://github.com/damm/ruby-backup.git"
end
```

How would you handle the not_if? as you don't want to reinstall the same thing over and over unless its changed.

**Comment by damm** [comment]
This is a few years old; I am going to close it.
