### ISSUE TITLE
get namespace backup from the chef supermarket

### ISSUE THREAD

**Issue by ramonskie** [damm/backup#40]
we need to try to get the backup namespace in the chef supermarket

see https://github.com/damm/backup/issues/31#issuecomment-155781665

**Comment by damm** [comment]
I'm not sure how we would do this; is there someone from Chef, Inc that could advise us on the process? is @guilhem willing?

**Comment by damm** [comment]
I emailed @nathenharvey as he was the one who moved it over to @guihem in the first place.

**Comment by damm** [comment]
It didn't go far; they want to see a bad track record of not responding to requests rather than a dormant or unsupported cookbook.  I did respond with my information but I never got a response back.

**Comment by rylarson** [comment]
Why not just publish it under a different name?

**Comment by guilhem** [comment]
@damm I can't change owner but I can release a new version
But try also: https://supermarket.chef.io/cookbooks/backup/adoption

Let me know if you have something to release

**Comment by rylarson** [comment]
@damm Releasing it to the community site under some other name would be really great. We want to use cookbooks like `bamboo`, but we use the community site along with our local supermarket and the discrepancy between two cookbooks with the same name makes it a huge pain.

I would be willing to bet that less people use it when it isn't released to Supermarket at all than if it was released under a different name.

**Comment by damm** [comment]
404 on https://supermarket.chef.io/cookbooks/backup/adoption

issue #31 highlights the problem of the naming convention (as we don't use a hwrp) we are locked to the cookbookname_#{resource} so `backup_install` becomes `backup_lwrp_install`

https://supermarket.chef.io/cookbooks/backup_lwrp

Really it's up to @ramonskie as that's his cookbook I believe?

**Comment by rylarson** [comment]
It is up to @ramonskie. The point I am trying to make is that if this is going to be useful to the masses, it can't break cookbooks that use it. 

Publishing it under a different name would allow it to be useful to the masses and cookbook authors who prefer to depend on it rather than the other `backup` cookbook.

**Comment by damm** [comment]
Ah see that is the problem once upon a time people depended on backup and got this.. but that was before fujin gave it to @guilhem 

Politics I guess and I have no interest in politics.  Forks happen and then re-forks?

**Comment by ramonskie** [comment]
i also don't see the issue why people have so much problems with the backup cookbook
that is set in the berks file
if you use berks (as this is the way to go in the chef community)
there should be no issue

i manage about 100 servers with hunderds of cookbooks
and i have no issues whats so ever

**Comment by guilhem** [comment]
IMHO, we can use same namespace with an upgrade on major version to explicit change of author / politic.

If some people don't use pessimistic.. shame on them.

**Comment by guilhem** [comment]
I now have rights on backup namespace on supermarket.

What I can propose is to migrate backup cookbook into http://github.com/redguide organisation, to create a team and add anyone of this team in supermarket.

**Comment by damm** [comment]
I'd rather make a org for this cookbook on it's own really; we can still add you me and whomever else else is interested in maintaining it.

**Comment by guilhem** [comment]
I really don't want to do a new org.
We creating Redguide specially to fix this kind of problem (see nodejs for example).
There is some guys from chef™ etc.
It's very important to have enough people in case a team become less active, some people from org can promote new guys to maintain.

**Comment by damm** [comment]
See that's a problem at this point I have a bit of ownership in this cookbook.  I'll give everyone who has contributed 110% credit because I am picky and sometimes either fix things to make me happy or ask people to.

But I really don't want to give up control as it previously was forked and uploaded as the backup cookbook without my permission.

If there's more work to be done in the future i'll be glad to accept help but I really don't envision anything in the pipeline

**Comment by guilhem** [comment]
Sorry @damm but that's exactly what I don't want to ear :/

In fact, current cookbook on supermarket isn't yours. It's https://github.com/gofullstack/backup-cookbook a totally different one.

I was proposing you to "merge" effort in a non-partisan organization... I'm sad to see so much attachement on ownership and not quality in an OSS project :disappointed:

**Comment by damm** [comment]
@guilhem no but at one point in time heavywater had forked this cookbook into github.com/heavywater/backup and uploaded it as the backup cookbook.  

I asked many times to be able to upload updates but they just treated it like their cookbook and took pull requests in.  After time fujin gave the cookbook namespace to you.

I really don't see a point in what your suggesting as I have never reviewed any code from you nor worked with you on anything.  

So as @ramonskie is happy with everything I suggest closing this issue as I don't really find it productive.

**Comment by damm** [comment]
I'd like to revisit this once Chef comes out of the dark ages with their Supermarket and starts to grow up (like docker hub or other sources).  We can then namespace this under `damm/backup` hopefully and resolve the minor issues when that happens.

@guilhem in the future it would be helpful to work with said people before making such an insane request.

Have a great weekend.
