### ISSUE TITLE
Support for Syncers

### ISSUE THREAD

**Issue by Sliim** [damm/backup#43]
Hi @damm 

do you planned to implement support for Syncers ? 
https://backup.github.io/backup/v4/syncers/

I'm interested for this so I think I will start a feature request shortly :)

**Comment by damm** [comment]
Had not thought about it; I've normally been doing backups the other way like storing a mysqldump on s3 or tar up a directory.  

Will be looking forward to that feature request.

**Comment by Sliim** [comment]
https://github.com/damm/backup/pull/44
