### ISSUE TITLE
Backup compression disabling is not available

### ISSUE THREAD

**Issue by Sp4rd4** [damm/backup#46]
Hi.
Great cookbook.
But I couldn't disable compression of backup, I could only chose different method (Gzip or Bzip2). 
Absence of `compress_with` in model generation block enables Gzip, putting `compress_with nil`, returns predictable error when performing backup.
I'm proposing using string "none" for `compress_with` for actually disabling the compression.
so now:
```
backup_generate_model "pg" do
...
compress_with "none"
...
end
```
will disable compressing of backup.

**Comment by damm** [comment]
You don't define compress_with; if it's defined... the problem is it is defined by default as Gzip; I suspect nil doesn't do what you want.

I pushed up an update where we don't define Gzip by default; see if that helps?

**Comment by Sp4rd4** [comment]
That definitely works for me, but I'm concerned that it would probably break backward compatibility for others, updating to this change may cause removal of compressing for existing models if compressing  wasn't defined explicitly. I would propose something like this in [generic_model.conf.erb](https://github.com/damm/backup/blob/master/templates/default/generic_model.conf.erb) instead of removing default value:
```
<% if @compress_with  && @compress_with != "none" %>
  compress_with <%= @compress_with %>
<% end %>
```

**Comment by damm** [comment]
backup gem is kind of weird; I actually have disabled compression by default w/ the backup gem on a few installs.  mysqldump + tar + another gzip on the side is a bit i/o work.  If it's already fairly compressed material it saves me a step of convolution when restoring.  

1. gunzip
2. untar
3. run mysql <

for example

**Comment by Sp4rd4** [comment]
Currently for one of my installs with this cookbook backup_generate_model block doesn't contain compress_with. But backups are compressed via Gzip. If version of cookbook wouldn't be specified in Berksfile next use of my cookbook on a new install will not enable compression of backup. For postgres dump of a size 20GB that could hurt. But I still prefer absence of compression by default.

**Comment by damm** [comment]
Yep and honestly gzip is pretty bad for compression.  I have one install where I run mysqldump manually into xz and have the backup gem upload the end results.

If you'd like I can release the cookbook with a new major version so we can make this breaking change easier to handle in our wrapper cookbooks?

**Comment by Sp4rd4** [comment]
That would be great, thanks!

**Comment by damm** [comment]
It should now be 0.3.0; if you want the old behavior look for older than 0.3.0 (0.2.6)
